global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@jandi.local'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        api: calendar
      receiver: 'calendar-alerts'
    - match:
        type: security
      receiver: 'security-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/critical'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'admin'
            password: 'secret'

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/warning'
        send_resolved: true

  - name: 'calendar-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/calendar'
        send_resolved: true

  - name: 'security-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/security'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance'] 