# Grafana 데이터 소스 자동 설정 - 로컬 개발 환경
# Grafana가 시작될 때 Prometheus를 데이터 소스로 자동 등록합니다.

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: 'prometheus' 