# Grafana 데이터 소스 자동 설정 - 운영 환경
# Grafana가 시작될 때 Prometheus를 데이터 소스로 자동 등록합니다.

apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      httpMethod: POST
      timeInterval: 5s 