spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.jackson.time-zone=Asia/Seoul
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
jwt.secret=${JWT_SECRET}
jwt.access-token-validity=1800000
jwt.refresh-token-validity=604800000
jwt.refresh-token-reissue-threshold=86400000
kakao.rest-api-key=${KAKAO_REST_API_KEY}
kakao.redirect-url=https://jandirhythmeet.netlify.app/callback
kakao.logout-url=https://kauth.kakao.com/oauth/logout
kakao.token-url=https://kauth.kakao.com/oauth/token
kakao.user-info-url=https://kapi.kakao.com/v2/user/me
kakao.user-unlink-url=https://kapi.kakao.com/v1/user/unlink
kakao.admin-key=${KAKAO_ADMIN_KEY}
image.storage.access-key=${IMAGE_STORAGE_ACCESS_KEY}
image.storage.secret-key=${IMAGE_STORAGE_SECRET_KEY}
image.storage.region=${IMAGE_STORAGE_REGION:auto}
image.storage.endpoint=${IMAGE_STORAGE_ENDPOINT}
image.storage.path-style=${IMAGE_STORAGE_PATH_STYLE:true}
image.storage.bucket=${IMAGE_STORAGE_BUCKET}
image.storage.public-url=${IMAGE_STORAGE_PUBLIC_URL}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
spring.data.redis.host=redis-17498.c340.ap-northeast-2-1.ec2.cloud.redislabs.com
spring.data.redis.port=17498
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=30000
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
invite.club.link.prefix=https://jandirhythmeet.netlify.app/invite/club/accept
invite.team.link.prefix=https://jandirhythmeet.netlify.app/invite/team/accept
invite.expire.days=7
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
user-withdraw.days=7
clubpending.expire.days=7
clubpending.expire.cron=0 0 0 * * ?
