bind 0.0.0.0
protected-mode yes
port 6379
databases 1
dir /data
appendonly yes
appendfsync everysec
save 3600 1 300 100 60 10000
maxmemory 128mb
maxmemory-policy noeviction
include /run/secrets/redis-auth.conf
