# Prometheus 설정 파일 - 운영 환경 (Ubuntu EC2)
# Spring Boot, Jenkins 애플리케이션 메트릭을 수집합니다.

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot 애플리케이션 메트릭만
  - job_name: 'jandi-band-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['rhythmeet-be:8080']
        labels:
          application: 'jandi_band_backend'
          environment: 'production'