# Prometheus 설정 파일 - 운영 환경 (Ubuntu EC2)
# Spring Boot, Jenkins 애플리케이션 메트릭을 수집합니다.

global:
  scrape_interval: 15s # 15초마다 메트릭 수집
  evaluation_interval: 15s # 15초마다 규칙 평가

# 메트릭 수집 대상 설정
scrape_configs:
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot 애플리케이션 메트릭 (실제 컨테이너명: rhythmeet-be)
  - job_name: 'jandi-band-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['rhythmeet-be:8080']
        labels:
          application: 'jandi_band_backend'
          environment: 'production'

  # Spring Boot 헬스체크
  - job_name: 'jandi-health-check'
    metrics_path: '/actuator/health'
    scrape_interval: 30s
    scrape_timeout: 15s
    static_configs:
      - targets: ['rhythmeet-be:8080']
        labels:
          check: 'health'
          environment: 'production'

  # Jenkins 메트릭 (실제 컨테이너명: jenkins)
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    scrape_interval: 30s
    scrape_timeout: 15s
    static_configs:
      - targets: ['jenkins:8080']
        labels:
          application: 'jenkins'
          environment: 'production'
    # Jenkins가 인증을 요구하는 경우 주석 해제
    # basic_auth:
    #   username: 'admin'
    #   password: 'your-jenkins-password' 